import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProviders";
import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/common/navbar";  
import Container from "@/components/common/container"
import Footer from "@/components/common/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="fixed top-0 left-0 right-0 z-50 w-full bg-background/80 backdrop-blur border-b">
          <Navbar /> 
        </div>
        <Container>
          <div className="pt-16">
            {children}
          </div>
        </Container>
        <Footer />
        <Toaster />
      </body>
      </AuthProvider>
    </html>
  );
}
